version: 2

orbs:
  win: circleci/windows@1.0.0

jobs:
  build_and_test_linux:
    docker:
      - image: ubuntu:bionic

    steps:
      - checkout

      - run:
          name: Install sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'

      - run:
          name: Install gcc
          command: 'apt-get update && apt-get install software-properties-common -y && add-apt-repository ppa:ubuntu-toolchain-r/test -y && apt-get update && apt-get install -y gcc-9 g++-9'

      - run:
          name: Install make
          command: 'apt-get update && apt-get install -y make'

      - run:
          name: Install wget
          command: 'apt-get update && apt-get install -y wget'

      - run:
          name: Install bzip2
          command: 'apt-get update && apt-get install -y bzip2'

      - run:
          name: Install git
          command: 'apt-get update && apt-get install -y git'

      - run:
          name: Install dependencies
          command: './install-deps.sh'

      - run:
          name: Install cmake
          command: 'mkdir cmake-src; cd cmake-src; wget https://github.com/Kitware/CMake/releases/download/v3.16.0-rc3/cmake-3.16.0-rc3-Linux-x86_64.sh; bash ./cmake-3.16.0-rc3-Linux-x86_64.sh --skip-license; cd ..'

      - run:
          name: Create build files
          command: 'CC=gcc-9 CXX=g++-9 cmake-src/bin/cmake -H. -Bbuild'

      - run:
          name: Build project
          command: 'cmake-src/bin/cmake --build build'

      - run:
          name: Test
          command: 'cmake-src/bin/cmake --build build --target test'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test_linux

