version: 2

orbs:
  win: circleci/windows@1.0.0

jobs:
  build_and_test_linux:
    docker:
      - image: gcc:9

    steps:
      - checkout

      - run:
          name: Install sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'

      - run:
          name: Install gcc
          command: 'apt-get update && apt-get install -y gcc g++'

      - run:
          name: Install make
          command: 'apt-get update && apt-get install -y make'

      - run:
          name: Install wget
          command: 'apt-get update && apt-get install -y wget'

      - run:
          name: Install bzip2
          command: 'apt-get update && apt-get install -y bzip2'

      - run:
          name: Install git
          command: 'apt-get update && apt-get install -y git'

      - run:
          name: Install boost
          command: 'wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2; tar --bzip2 -xf boost_1_66_0.tar.bz2; ln -s `pwd`/boost_1_66_0/boost /usr/include'

      - run:
          name: Install cmake
          command: 'mkdir cmake; cd cmake; wget https://github.com/Kitware/CMake/releases/download/v3.16.0-rc3/cmake-3.16.0-rc3-Linux-x86_64.sh; bash ./cmake-3.16.0-rc3-Linux-x86_64.sh --skip-license; cd ..'

      - run:
          name: Create build files
          command: './cmake/bin/cmake -H. -Bbuild'

      - run:
          name: Build project
          command: './cmake/bin/cmake --build build'

      - run:
          name: Test
          command: './hypergraph/test/hypergraph_test'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test_linux

