version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y g++'

      - run:
          name: Install CMake
          command: 'apt-get update && sudo apt-get install -y cmake'

      - run:
          name: Build
          command: 'mkdir build; cmake ..; make'

      - run:
          name: Test
          command: './hypergraph/test/hypergraph_test'
