version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'

      - run:
          name: Install gcc
          command: 'apt-get update && apt-get install -y gcc g++'

      - run:
          name: Install cmake
          command: 'apt-get update && sudo apt-get install -y cmake'

      - run:
          name: Build
          command: 'mkdir build; cmake ..; make'

      - run:
          name: Test
          command: './hypergraph/test/hypergraph_test'
