# Generate instances of the planted constant rank hypergraph family
type: planted_constant_rank

# Number of times to repeat each algorithm
num_runs: 20

cutoff: True

percentages:
  - 8
  - 10
  - 12
  - 15
  - 17
  - 20
  - 12
  - 25
  - 33
  - 50
  - 100
  - 200

# Generate instances with these number of vertices
num_vertices:
  - 350

# Number of clusters
k: 2

# Rank of each hyperedge
rank: 3

# Set `m2` (number of crossing hyperedges) to `n / m2_mult`
m2_mult: 10

# Set `m1` (number of non-crossing hyperedges) to `m2 * m1_mult`
m1_mult: 100
