# Generate instances of the ring hypergraph family
type: ring

# Number of times to repeat each algorithm
num_runs: 20

cutoff: True

percentages:
  - 8
  - 10
  - 12
  - 14
  - 16
  - 18
  - 20
  - 25
  - 33
  - 50
  - 100
  - 200

# Generate instances with these number of vertices. The largest size will be ~50k.
# Hypergraphs with skewed cuts are commented out
num_vertices:
  - 225

# Generate `edge_mult * n` hyperedges where `n` is the number of vertices
edge_mult: 30

# The radius of each hyperedge in degrees
radius: 15
