# Generate instances of the ring hypergraph family
type: ring

# Number of times to repeat each algorithm
num_runs: 20

# Generate instances with these number of vertices. The largest size will be ~50k.
# Hypergraphs with skewed cuts are commented out
num_vertices:
  # - 100
  - 112
  - 125
  # - 137
  - 150
  # - 162
  - 175
  - 187
  # - 200
  - 217
  - 225
  # - 250

# Generate `edge_mult * n` hyperedges where `n` is the number of vertices
edge_mult: 30

# The radius of each hyperedge in degrees
radius: 15
