# Generate instances of the ring hypergraph family
type: ring

# Number of times to repeat each algorithm
num_runs: 20

cutoff: True

percentages:
  - 0.08
  - 0.10
  - 0.12
  - 0.14
  - 0.16
  - 0.18
  - 0.20
  - 0.25
  - 0.33
  - 0.50
  - 1.00
  - 2.00

# Generate instances with these number of vertices. The largest size will be ~50k.
# Hypergraphs with skewed cuts are commented out
num_vertices:
  - 225

# Generate `edge_mult * n` hyperedges where `n` is the number of vertices
edge_mult: 30

# The radius of each hyperedge in degrees
radius: 15
