name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu:
    name: ${{ matrix.os }}-${{ matrix.cxx }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cxx: [g++-10]
        os: [ubuntu-18.04]
    env:
      CXX: ${{ matrix.cxx }}
    steps:
      - name: checkout
        uses: actions/checkout@master
        with: { submodules: true }
      - name: toolchain
        run: |
          set -e
          sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
          sudo -E apt-get -o Acquire::Retries=3 -yq --no-install-suggests --no-install-recommends install ${CXX}
      - name: dependencies
        run: |
          set -e
          sudo -E ./install-deps.sh
      - name: configure
        run: cmake -H. -Bbuild
      - name: build
        run: cmake --build build
      - name: test
        run: cmake --build build --target test
