name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu:
    name: ${{ matrix.os }}-${{ matrix.cxx }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cxx: [clang-10, g++-10]
        os: [ubuntu-18.04]
        include:
          - cxx: clang-10
            os: ubuntu-18.04
            CXX: clang++-10
            llvm-os-name: bionic
            llvm-version: 10
          - cxx: g++-10
            CXX: g++-10
    env:
      CXX: ${{ matrix.CXX }}
      LLVM_VERSION: ${{ matrix.llvm-version }}
      LLVM_OS_NAME: ${{ matrix.llvm-os-name }}
    steps:
      - name: checkout
        uses: actions/checkout@master
        with: { submodules: true }
      - name: toolchain
        run: |
          set -e
          if test -n "${LLVM_OS_NAME}" ; then
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo -E apt-add-repository "deb http://apt.llvm.org/${LLVM_OS_NAME}/ llvm-toolchain-${LLVM_OS_NAME}-${LLVM_VERSION} main"
          else
            sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
          fi
          sudo -E apt-get -o Acquire::Retries=3 -yq --no-install-suggests --no-install-recommends install ${CXX}
      - name: dependencies
        run: |
          set -e
          sudo -E ./install-deps.sh
      - name: configure
        run: cmake -H. -Bbuild
      - name: build
        run: cmake --build build
      - name: test
        run: cmake --build build --target test
