name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu:
    name: ${{ matrix.os }}-${{ matrix.cxx }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cxx: [g++-7, g++-8, g++-9, g++-10, clang++-7, clang++-8, clang++-9, clang++-10]
        os: [ubuntu-16.04, ubuntu-18.04]
    env:
      CXX: ${{ matrix.cxx }}
    steps:
      - name: checkout
        uses: actions/checkout@master
        with: { submodules: true }
      - name: configure
        run: cmake -H. -Bbuild
      - name: build
        run: cmake --build build
      - name: test
        run: cmake --build build --target test
